name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM
      run: brew install llvm@11
    - name: Get Dependencies
      run: swift package resolve
    - name: Make pkgconfig
      run: swift ./utils/make-pkgconfig.swift
    - name: Build
      run: swift build -v
